[global]
# 开发模式设置
developmentMode = false

# 数据框显示设置
dataFrameSerialization = "legacy"

[server]
# 服务器设置
port = 8501
enableCORS = false
enableXsrfProtection = false

# 文件上传设置
maxUploadSize = 200
maxMessageSize = 200

# WebSocket设置
enableWebsocketCompression = false

[browser]
# 浏览器设置
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# 主题设置
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# 客户端设置
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
# 运行器设置
magicEnabled = true
installTracer = false
fixMatplotlib = true

# 快速重新运行
fastReruns = true

# 强制重新运行超时
enforceSerializableSessionState = false

