# Streamlit Secrets Configuration
# 这个文件用于存储敏感配置信息，不应提交到版本控制

# 数据库连接（如果需要）
# [database]
# host = "your-database-host"
# port = 5432
# database = "your-database-name"
# username = "your-username"
# password = "your-password"

# API密钥（如果需要）
# [api_keys]
# openai_api_key = "your-openai-api-key"
# other_api_key = "your-other-api-key"

# 服务器默认配置（示例）
# [default_server]
# host = "your-default-server-host"
# port = 22
# username = "your-username"
# # 注意：不要在这里存储密码，使用SSH密钥认证

# 应用配置
[app]
# 应用名称
name = "电池寿命预测系统"
version = "1.0.0"
author = "浙江锋锂新能源科技有限公司-唐光盛团队"

# 功能开关
enable_server_connection = true
enable_model_optimization = true
enable_advanced_features = true

# 文件大小限制（MB）
max_file_size = 100

# 模型配置
[models]
default_algorithm = "XGBoost"
max_training_time = 3600  # 秒
enable_gpu = false

# 安全配置
[security]
# 加密密钥（生产环境中应使用环境变量）
# encryption_key = "your-encryption-key"

# 会话超时（分钟）
session_timeout = 60

# 最大并发连接数
max_connections = 10

